name: Are They Awake Yet
on: [issues, pull_request]
jobs:
  are-they-awake-yet:
    runs-on: ubuntu-latest
    steps:
    - name: are-they-awake-yet
      uses: benhayehudi/awake-yet-action@master
    env:
      GITHUB_TOKEN: "${{ secrets.TOKEN }}"
      GOOGLE_API_KEY: "${{ secrets.API_KEY }}"
